name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './react-portfolio/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd react-portfolio
          npm ci
      
      - name: Build for GitHub Pages
        run: |
          cd react-portfolio
          npm run build
      
      - name: Build for Custom Domain
        run: |
          cd react-portfolio
          # Temporarily change base path for custom domain build
          sed -i 's|base: '\''/alichaaraoui.com/'\'',|base: '\''/'\'',|g' vite.config.js
          npm run build
          # Copy custom domain build to a separate folder
          cp -r dist dist-custom
          # Restore original vite.config.js
          git checkout vite.config.js
      
      - name: Prepare Deployment
        run: |
          cd react-portfolio
          # For custom domain, we need the root-optimized version
          # Copy custom domain files to main dist folder
          cp -r dist-custom/* dist/
          # Fix any remaining paths
          find dist/assets -name "*.js" -exec sed -i 's|/alichaaraoui.com/CELINE/|/CELINE/|g' {} \;
          find dist/assets -name "*.js" -exec sed -i 's|/alichaaraoui.com/fonts/|/fonts/|g' {} \;
          find dist/assets -name "*.js" -exec sed -i 's|/alichaaraoui.com/public/|/public/|g' {} \;
          find dist/assets -name "*.js" -exec sed -i 's|/react-portfolio/CELINE/|/CELINE/|g' {} \;
          find dist/assets -name "*.js" -exec sed -i 's|/react-portfolio/fonts/|/fonts/|g' {} \;
          find dist/assets -name "*.js" -exec sed -i 's|/react-portfolio/public/|/public/|g' {} \;
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './react-portfolio/dist'
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


